include $(TOPDIR)/rules.mk

PKG_MAINTAINER:=Alexey Smirnov <s.alexey@gmail.com>
PKG_NAME:=luci-app-ethstat
PKG_LICENSE:=Apache-2.0

LUCI_TITLE:=OMAP am335x ethernet statistic display
LUCI_DEPENDS:=+luci-base +ethtool
LUCI_PKGARCH:=all

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
