include $(TOPDIR)/rules.mk

PKG_MAINTAINER:=Alexey Smirnov <s.alexey@gmail.com>
PKG_NAME:=luci-app-mcast
PKG_LICENSE:=Apache-2.0

LUCI_TITLE:=Multicast status and statistic display
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
